namespace Modules.AssetsEditor.Localization;

public sealed record UiHelp(string Label, string Tip);

public static class AssetsEditorLabels
{
    public static readonly IReadOnlyDictionary<string, UiHelp> Flags = new Dictionary<string, UiHelp>
    {
        ["Transparency"] = new("Transparency", "Poziom przezroczystości obiektu."),
        ["Bank"] = new("Ground", "Obiekt działa jak podłoże i wpływa na chodzenie postaci."),
        ["Clip"] = new("Clip", "Sprite jest przycinany przez klienta."),
        ["Bottom"] = new("Bottom", "Obiekt rysuje się jako dolna część pola."),
        ["Top"] = new("Top", "Obiekt rysuje się nad innymi elementami pola."),
        ["Container"] = new("Container", "Obiekt może być kontenerem."),
        ["Cumulative"] = new("Cumulative", "Obiekt może składać się w stos."),
        ["Usable"] = new("Usable", "Gracz może użyć obiektu."),
        ["Forceuse"] = new("Forceuse", "Klient wymusza akcję użycia."),
        ["Multiuse"] = new("Multiuse", "Obiekt obsługuje użycie na innym celu."),
        ["Write"] = new("Write", "Na obiekcie można zapisać tekst."),
        ["WriteOnce"] = new("Write Once", "Tekst można zapisać tylko raz."),
        ["Liquidpool"] = new("Liquid Pool", "Obiekt jest polem płynu na mapie."),
        ["Unpass"] = new("Unpass", "Nie da się przejść przez obiekt."),
        ["Unmove"] = new("Unmove", "Gracz nie może przesunąć obiektu."),
        ["Unsight"] = new("Unsight", "Obiekt zasłania linię widzenia."),
        ["Avoid"] = new("Avoid", "Pathfinding powinien unikać tego obiektu."),
        ["NoMovementAnimation"] = new("No Move Animation", "Wyłącza animację ruchu dla obiektu."),
        ["Take"] = new("Take", "Obiekt można zabrać do ekwipunku."),
        ["Liquidcontainer"] = new("Liquid Container", "Obiekt może przechowywać płyn."),
        ["Hang"] = new("Hang", "Obiekt można wieszać na ścianie."),
        ["Hook"] = new("Hook", "Obiekt jest hakiem albo miejscem zawieszenia."),
        ["HookSouth"] = new("Hook South", "Hak działa od południa."),
        ["HookEast"] = new("Hook East", "Hak działa od wschodu."),
        ["Rotate"] = new("Rotate", "Obiekt może zostać obrócony."),
        ["Light"] = new("Light", "Obiekt emituje światło."),
        ["DontHide"] = new("Dont Hide", "Klient nie powinien ukrywać obiektu."),
        ["Translucent"] = new("Translucent", "Obiekt jest rysowany jako półprzezroczysty."),
        ["Shift"] = new("Shift", "Przesuwa rysowanie sprite'a względem pola."),
        ["Height"] = new("Height", "Wysokość obiektu wpływająca na rysowanie i stosowanie."),
        ["ReverseAddons"] = new("Reverse addons", "Odwraca nakładanie addonów dla kierunków stroju."),
        ["LyingObject"] = new("Lying Object", "Obiekt jest traktowany jako leżący."),
        ["AnimateAlways"] = new("Animate Always", "Animacja działa cały czas, nie tylko w wybranych stanach."),
        ["Automap"] = new("Auto Map", "Obiekt ma kolor na minimapie."),
        ["Lenshelp"] = new("Lens help", "ID podpowiedzi używane przez klienta przy oglądaniu obiektu."),
        ["Fullbank"] = new("Full Ground", "Pełny wariant podłoża lub banku ruchu."),
        ["IgnoreLook"] = new("Ignore Look", "Obiekt ignoruje akcję patrzenia."),
        ["Clothes"] = new("Clothes", "Obiekt zajmuje slot ekwipunku."),
        ["DefaultAction"] = new("Default Action", "Domyślna akcja klienta dla obiektu."),
        ["Market"] = new("Market", "Obiekt jest widoczny w markecie."),
        ["Wrap"] = new("Wrap", "Obiekt obsługuje akcję zawinięcia."),
        ["Unwrap"] = new("Unwrap", "Obiekt obsługuje akcję odwinięcia."),
        ["Topeffect"] = new("Top Effect", "Efekt rysuje się nad innymi elementami."),
        ["DecoItemKit"] = new("Deco Item Kit", "Obiekt jest częścią systemu dekoracji."),
        ["Changedtoexpire"] = new("Changed To Expire", "Obiekt zmienia się na inny po wygaśnięciu."),
        ["Corpse"] = new("Corpse", "Obiekt jest ciałem lub zwłokami."),
        ["PlayerCorpse"] = new("Player Corpse", "Obiekt jest ciałem gracza."),
        ["Npcsaledata"] = new("Npc Sale Data", "Lista ofert NPC: nazwa, lokalizacja, ceny i waluta."),
        ["ShowOffSocket"] = new("Podium", "Flaga ShowOffSocket używana przez klienta dla podium."),
        ["Reportable"] = new("Reportable", "Obiekt może być zgłaszany w kliencie."),
        ["Upgradeclassification"] = new("Upgrade classification", "Klasa ulepszenia używana przez klienta."),
        ["Wearout"] = new("Wearout", "Obiekt może się zużywać."),
        ["Clockexpire"] = new("Clock expire", "Wygaśnięcie liczone zegarem."),
        ["Expire"] = new("Expire", "Obiekt ma mechanizm wygaśnięcia."),
        ["Expirestop"] = new("Expire stop", "Zatrzymuje mechanizm wygaśnięcia."),
        ["Cyclopediaitem"] = new("Cyclopedia", "Obiekt jest widoczny w Cyclopedii."),
        ["Ammo"] = new("Ammo", "Obiekt jest amunicją."),
        ["SkillwheelGem"] = new("WheelGem", "Obiekt jest klejnotem koła umiejętności."),
        ["DualWielding"] = new("Dual Wielding", "Obiekt wspiera walkę dwiema broniami."),
        ["Imbueable"] = new("Imbueable", "Obiekt można imbuować."),
        ["Proficiency"] = new("Proficiency", "Obiekt ma wymaganie albo oznaczenie biegłości."),
        ["MinimumLevel"] = new("Minimum Level", "Minimalny poziom wymagany do użycia."),
        ["WeaponType"] = new("Weapon Type", "Typ broni zapisany dla obiektu."),
        ["RestrictToVocation"] = new("Restrict Vocation", "Lista profesji, które mogą używać obiektu."),

        ["TextureLayers"] = new("Warstwy ?", "Liczba warstw sprite'a."),
        ["TextureFrames"] = new("Klatki ?", "Liczba klatek animacji."),
        ["TexturePatternX"] = new("Szerokość wzoru ?", "Liczba wariantów w osi X."),
        ["TexturePatternY"] = new("Wysokość wzoru ?", "Liczba wariantów w osi Y."),
        ["TexturePatternZ"] = new("Głębia wzoru ?", "Liczba wariantów w osi Z."),
        ["TextureBoundingSquare"] = new("Kwadrat kolizji ?", "Orientacyjny obszar obiektu dla klienta."),
        ["TextureOpaque"] = new("Nieprzezroczysty ?", "Flaga braku przezroczystości tekstury."),
        ["AnimationStartPhase"] = new("Domyślna faza startowa ?", "Domyślna klatka startowa animacji."),
        ["AnimationLoopType"] = new("Typ pętli ?", "Sposób powtarzania animacji."),
        ["AnimationLoopCount"] = new("Liczba pętli ?", "Liczba powtórzeń animacji."),
        ["BoundingBoxPerDirection"] = new("Prostokąt kolizji według kierunku ?", "Osobne prostokąty kolizji dla kierunków obiektu.")
    };
}
